Initial commit of graphdb widl
wasmCloud/actor-interfaces pull request #20
Opened 2021-01-13 20:20 UTC by brooksmtownsend

Working towards fixing #4 .

Making sure I'm on the right track here, I've put in the `QueryGraph` and `DeleteGraph` operations, that seems to be what is implemented in the current redisgraph provider. I'll begin the implementation once I know that I'm not going down a dark path 😉

2021-01-13 21:07 UTC, autodidaddict commented
Take a look at https://github.com/wasmCloud/capability-providers/tree/main/redisgraph/crates/common , once you've got the messagepack schema / widl done, then the actor interface crate should contain the common stuff from here. This is the wrapper code that lets you query/extract tuples from the raw data.

2021-01-14 14:26 UTC, autodidaddict commented
I am worried about this one because we, as a general rule, try and build these in a way that aren't language specific. I know that the current version is very Rust-specific. 

I think what we need to do is find some generic "raw data" format to use for the schema that can then be converted into the more robust type in use by the rust interface. This is made slightly more difficult by the fact that widl doesn't do enums.

2021-01-14 17:10 UTC, autodidaddict commented on schemas/graphdb.widl
> +	stringValue: bytes?
A field called `stringValue` should probably be a `string?` rather than `bytes?` right?

2021-01-14 17:11 UTC, autodidaddict requested changes

2021-01-14 17:11 UTC, autodidaddict commented on schemas/graphdb.widl
> +	type_name: string
I think this is supposed to be `typeName`. @pkedy can correct me if I'm wrong, but I think we want the widl to be all camel cased and then the language-specific generators will give us what we expect.

2021-01-14 17:15 UTC, brooksmtownsend commented on schemas/graphdb.widl
> +	stringValue: bytes?
That would make sense yes, I based this off of https://github.com/wasmCloud/capability-providers/blob/main/redisgraph/crates/common/src/lib.rs#L222-L224 but its possible I misunderstood (or took the Rust implementation too literally)

2021-01-14 17:16 UTC, brooksmtownsend commented on schemas/graphdb.widl
> +	type_name: string
Good to know, I used snake case in a few other places too. I'll fix those up 👍

2021-01-14 17:18 UTC, autodidaddict commented
Oh I think that's an internal implementation detail where the string comes
out of the query response as a byte array. I think on the "wire" it should
be a string but we'll only find out after refactoring the provider 😀

On Thu, Jan 14, 2021, 12:16 PM Brooks Townsend <notifications@github.com>
wrote:

> *@brooksmtownsend* commented on this pull request.
> ------------------------------
>
> In schemas/graphdb.widl
> <https://github.com/wasmCloud/actor-interfaces/pull/20#discussion_r557559270>
> :
>
> > +}
>
> +
>
> +type Scalar {
>
> +	boolValue: bool?
>
> +	intValue: i64?
>
> +	doubleValue: f64?
>
> +	stringValue: bytes?
>
> +}
>
> +
>
> +type Node {
>
> +	labels: [string]
>
> +	properties: {string:Scalar}
>
> +}
>
> +
>
> +type Relation {
>
> +	type_name: string
>
>
> Good to know, I used snake case in a few other places too. I'll fix those
> up 👍
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/wasmCloud/actor-interfaces/pull/20#discussion_r557559270>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADI4TIMLFCOXNOVC65KZRRLSZ4RG3ANCNFSM4WBLVC7Q>
> .
>

2021-01-19 22:22 UTC, brooksmtownsend commented
Marking as `do not merge` while I work on refactoring the graphdb provider

2021-01-20 19:14 UTC, brooksmtownsend commented
@autodidaddict I've opened a PR for the redisgraph provider & actor API that use these interfaces and they work well, do you have any additional thoughts here? https://github.com/wasmCloud/capability-providers/pull/21

2021-01-25 17:29 UTC, autodidaddict commented
@brooksmtownsend what's the status of this one?

2021-01-25 17:35 UTC, brooksmtownsend commented
@autodidaddict This one should be good to go, unless you have further suggested changes

2021-01-25 21:29 UTC, autodidaddict requested changes

2021-01-25 21:29 UTC, autodidaddict commented on schemas/graphdb.widl
> +type QueryResponse {
Query Response here is still `bytes`, this shouldn't be bytes, it should be the wire format data that has the result set, etc.

2021-01-25 21:51 UTC, brooksmtownsend commented on schemas/graphdb.widl
> +type QueryResponse {
>wire format data
Wouldn't wire format data be bytes? I might be misunderstanding you here. I can see it making sense as a `ResultSet`, as that's feasibly what you'd get back from a query, but I want to make sure I understand correct

2021-01-26 16:36 UTC, autodidaddict requested changes

2021-01-26 16:36 UTC, autodidaddict commented on rust/graphdb/Cargo.toml
> +wascc-actor = "0.7.4"
wascc-actor is deprecated. We should probably publish a deprecated/removed flag to crates dot io

2021-01-26 16:36 UTC, autodidaddict commented on rust/graphdb/src/lib.rs
> +mod conversions;
Those conversions are either going to need to be a public module or re-exported as public types from the root of this crate. If actors can't access the conversions, they can't do actual graph queries.

we really should have a unit test (or even a doc test) that proves that we can compile actor code that performs a graph query. There's an example unit test floating around that proved such a query was possible. We should probably put that into a doc test, hide the function that returns fake data, and use that to certify the conversions are available to graph db actors.

2021-01-26 16:40 UTC, autodidaddict commented
Let's also make sure that we have a functioning graph database example that uses this actor interface and the redisgraph provider to verify both sides of this conversation before we flag this work as done.

2021-01-26 16:41 UTC, brooksmtownsend commented on rust/graphdb/src/lib.rs
> +mod conversions;
So, checking with https://github.com/wasmCloud/capability-providers/pull/21, I was able to compile the sample graph actor with this interface, so it does at least compile from the query standpoint. Agreed with your point in the later comment that we should run an example with this, the redisgraph provider, and a redisgraph instance to test

2021-01-26 17:22 UTC, autodidaddict commented on rust/graphdb/src/lib.rs
> +mod conversions;
:thinking: hah... I wonder what sort of sorcery makes those traits magically visible to consumers without being in a public module.

2021-02-01 15:59 UTC, brooksmtownsend commented
@autodidaddict ready for re-review here after confirming working interaction with this interface between graphdb sample actor and redisgraph provider. Once this is ready to go, https://github.com/wasmCloud/capability-providers/pull/21 can be updated to use this interface and we can fix the tests passing there

2021-02-02 21:34 UTC, autodidaddict approved these changes

2021-02-02 21:34 UTC, autodidaddict commented on rust/graphdb/Cargo.toml
> +keywords = ["webassembly", "wasm", "wasmcloud", "actor"]
should we add `graph` or `graphdb` as a tag here so that both the actor interface and provider show up in a crates search for graph?

2021-02-02 21:35 UTC, brooksmtownsend commented on rust/graphdb/Cargo.toml
> +keywords = ["webassembly", "wasm", "wasmcloud", "actor"]
Good idea, I'll add both real quick

2021-02-02 21:37 UTC, merged