Implemented logging interface
wasmCloud/actor-interfaces pull request #29
Opened 2021-01-22 16:39 UTC by brooksmtownsend

Fixes #27

2021-01-25 21:44 UTC, autodidaddict requested changes

2021-01-25 21:44 UTC, autodidaddict commented on rust/logging/src/lib.rs
> +// extern crate wapc_guest as guest;
you need to use `//!` for the rustdoc... these are just going to show up as regular comments and not appear in the rustdoc.

Prior to publishing any crate, I typically run `cargo doc --no-deps --lib --open` to preview the rustdoc before publication. Also, running `cargo test` should execute the doctest. If you have 0 doctests then you know that the rust doc for the module isn't correct.

2021-02-04 20:16 UTC, autodidaddict requested changes

2021-02-04 20:16 UTC, autodidaddict commented on rust/logging/Cargo.toml
> +serde_json = "1.0.57"
do we really need serde_json for the logging interface? If we only need it for the doctest, then we should strip out the unused dependencies here to keep the crate size small.

2021-02-04 20:16 UTC, autodidaddict commented on rust/logging/Cargo.toml
> +[profile.release]
This profile.release is really only used for a `.wasm` target. Since this is an actor interface that isn't designed to produce a standalone wasm, we should remove this.

2021-02-04 20:16 UTC, autodidaddict commented on rust/logging/Makefile
> +build:
Since this is a reusable crate designed for use by either capability provider or by actor, we shouldn't have a build task here that produces a wasm file, since it essentially wouldn't do anyone any good.

2021-02-04 20:16 UTC, autodidaddict commented on rust/logging/src/generated.rs
> +    pub fn write_log(&self, request: WriteLogRequest) -> HandlerResult<()> {
We should add a doc comment to all of these functions so that it shows up in the docs.rs documentation and on hover-over in IDEs like VScode.

2021-02-04 20:16 UTC, autodidaddict commented on rust/logging/src/generated.rs
> +    pub fn register_write_log(f: fn(WriteLogRequest) -> HandlerResult<()>) {
We should remove the handlers struct because actors never handle the "write log" message.

2021-02-05 18:17 UTC, brooksmtownsend commented on rust/logging/src/generated.rs
> +    pub fn write_log(&self, request: WriteLogRequest) -> HandlerResult<()> {
I have a question here, do actors simply just call `info` / `trace` level `log` macros and have `write_log` automatically invoked? Or will actors need to manually call `write_log`? If it's the former, then I don't think this function needs to be public or used by actors, but if it's the latter then we may want to change the WIDL to allow for a log level, and a log to pass to this function. I was under the impression that `log` macros were intercepted somehow when logged at the actor level, which then is actually logged by the provider.

2021-02-08 14:48 UTC, autodidaddict commented on rust/logging/src/generated.rs
> +    pub fn write_log(&self, request: WriteLogRequest) -> HandlerResult<()> {
The original code that set up the logger implementation that provided a front-end to the logging interface could be found in [wascc-actor](https://github.com/wasmCloud/wascc-actor/blob/master/src/logger.rs). We should migrate that stuff into actor-core so that any time an actor uses the `info!` and `warn!` etc macros, it sends `wasmcloud:logging` requests. This is basically required to make the code work as our code sample illustrates.

2021-02-08 15:36 UTC, brooksmtownsend commented on rust/logging/src/generated.rs
> +    pub fn write_log(&self, request: WriteLogRequest) -> HandlerResult<()> {
As per our discussion in Slack, the goal here will be to improve `write_log` to accept the individual parameters instead of a request object and to implement the log macro interception in the Rust interface.

2021-02-08 16:49 UTC, brooksmtownsend commented
![image](https://user-images.githubusercontent.com/12040685/107252521-6d87e200-6a03-11eb-994f-9e0ffdc94d8a.png)
@autodidaddict Here's the rustdoc preview (just so you can see it here) for the latest commits. I've restructured a few parts in the code, that way we can use `write_log` directly to write logs, OR for Rust you can initialize the logger with `logger::use_macros()` and it will intercept macros like `info`, `debug`, etc. Some form of initialization is required here, which was originally being done [here](https://github.com/wasmCloud/wascc-actor/blob/master/src/lib.rs#L49).

2021-02-08 16:54 UTC, autodidaddict commented
Maybe we should show this being executed as the first function inside `wapc_init`, which maybe gives a better perspective on when/how this thing should run. It's not run as or inside a message handler, it's run during the init function (which should theoretically get called only once during the lifetime of the module).

Also, what do you think of `enable_macros` instead of `use_macros` ?

2021-02-08 17:16 UTC, brooksmtownsend commented
> Maybe we should show this being executed as the first function inside `wapc_init`, which maybe gives a better perspective on when/how this thing should run. It's not run as or inside a message handler, it's run during the init function (which should theoretically get called only once during the lifetime of the module).
> 
> Also, what do you think of `enable_macros` instead of `use_macros` ?

I like both of these changes, and changing it to `enable_macros` makes better sense than `use`. It's probably better idiomatic rust to avoid a reserved keyword in a method name.

2021-02-08 17:28 UTC, autodidaddict commented on logging/rust/src/lib.rs
> +        enable_macros();
Why is `enable_macros` being called from inside `write_log` ?

2021-02-08 17:31 UTC, autodidaddict requested changes

2021-02-08 17:31 UTC, autodidaddict commented on logging/rust/src/lib.rs
> +        if self.enabled(record.metadata()) {
If we know that enabled is always true, regardless of the logger metadata, we don't need to actually call that again in the `log` method

2021-02-08 18:08 UTC, brooksmtownsend commented on logging/rust/src/lib.rs
> +        enable_macros();
Ah this looks leftover from when I was brainstorming on how to ensure that the logger was "initialized". This should be removed

2021-02-08 21:01 UTC, autodidaddict approved these changes

2021-02-08 21:04 UTC, merged