Implemented blobstore interface in rust, wrote schema
wasmCloud/actor-interfaces pull request #30
Opened 2021-01-22 17:06 UTC by brooksmtownsend

Going to lean on @autodidaddict a bit here to take a look over the schema, I took my best guess at appropriate `void` return types and parameters (e.g. using `Container` type for `container` field) so just looking for some validation this was done appropriately.

Fixes #28

2021-01-22 18:37 UTC, autodidaddict requested changes
The first thing I would say is attempt to go through a demo of a file system-based actor (we have some in `gantry` that we could use for examples) and see if this works.

Secondly, we should remove the host stuff that doesn't apply and remove the guest stuff that doesn't apply.

Guests can only register a `ReceiveChunk` handler, and all other functions in the interface are ones that are supplied by the host. For confirmation of this, you can look at the outdated capability provider code for the file system or S3, and you'll see in the descriptor code which way the functions go.

@pkedy we really need a way to describe the operation _direction_ in the interface so that when we generate, we don't have to continually re-delete the stuff that isn't supported.

2021-01-22 18:38 UTC, autodidaddict commented on rust/blobstore/src/lib.rs
> +//     Handlers::register_receive_chunk(receive_chunk);
The only one of these registers that is applicable to a guest actor is `register_receive_chunk`

2021-01-28 21:27 UTC, autodidaddict commented
@brooksmtownsend is this in the pipeline after graphdb?

2021-01-28 21:31 UTC, brooksmtownsend commented
@autodidaddict Yep, this is on my todo after Graphdb. I was going to approach this in the same way, working to go through a demo of a filesystem actor to ensure we're still functional

2021-02-02 17:13 UTC, autodidaddict commented on rust/blobstore/src/lib.rs
> +//! fn download_poem(req: http::Request) -> HandlerResult<http::Response> {
:heart: :heart_eyes:

2021-02-02 17:30 UTC, merged