Rust httpclient interface
wasmCloud/actor-interfaces pull request #37
Opened 2021-02-04 20:24 UTC by brooksmtownsend

2021-02-04 20:38 UTC, autodidaddict requested changes

2021-02-04 20:38 UTC, autodidaddict commented on http-client/httpclient.widl
>    path: string
do we really need path and method on this request... or should we modify the operation so it has easier to describe operations, e.g. 
```
Request(method: string, url: string, headers: {string, string}): Response
```

2021-02-04 20:38 UTC, autodidaddict commented on http-client/rust/Cargo.toml
> +description = "HTTP Server Actor Interface for waSCC Actors"
should be "HTTP Client Actor Interface for wasmCloud Actors"

2021-02-04 20:38 UTC, autodidaddict commented on http-client/rust/Cargo.toml
> +serde_json = "1.0.57"
Make sure we need all of these dependencies for the core library. If not, we can leave them as dev-dependencies for the doctest.

2021-02-04 20:38 UTC, autodidaddict commented on http-client/rust/Cargo.toml
> +[profile.release]
actor interfaces shouldn't be compiled as standalone targets, so we should remove this... as well as the build task from the makefile.

2021-02-04 20:38 UTC, autodidaddict commented on http-client/rust/src/generated.rs
> +impl Handlers {
http client has no handlers, so we should remove the handlers portion of this file.

2021-02-04 20:38 UTC, autodidaddict commented on http-client/rust/src/generated.rs
> +    pub fn handle_request(&self, request: Request) -> HandlerResult<Response> {
See my previous comment. I think we can make a better widl description for performing a request, and remove the "handle_" while we're at it.

2021-02-04 20:38 UTC, autodidaddict commented on http-client/rust/src/lib.rs
> +//! const API_FQDN: &str = "wasmcloudapi.amazonaws.com"; // Not real
If this isn't real, we should probably not use a specific cloud provider. Maybe we can make one up :)

2021-02-04 20:49 UTC, brooksmtownsend commented on http-client/rust/Cargo.toml
> +description = "HTTP Server Actor Interface for waSCC Actors"
doh

2021-02-04 21:28 UTC, brooksmtownsend commented on http-client/httpclient.widl
>    path: string
I like that way of describing it, especially since you don't generally construct a request object, you just _make_ that request.

2021-02-04 21:51 UTC, autodidaddict requested changes

2021-02-04 21:51 UTC, autodidaddict commented on http-client/rust/src/generated.rs
> +    pub fn request(
I know this got regenerated, but we should add doc comments to public methods that actor developers will use.

2021-02-04 21:51 UTC, autodidaddict commented on http-client/rust/src/generated.rs
> +    static ref REQUEST: RwLock<
we can get rid of this stuff and the `Handlers` struct because request is one-way to the provider, actors can't handle it.

2021-02-04 21:51 UTC, autodidaddict commented on http-client/rust/src/lib.rs
> +//!         let res = request(msg.method, API_URL.to_string(), msg.header)?;
Add a comment here like we had last time that tells people what to replace the hack method with, e.g. `httpclient::default().request(....)`

2021-02-05 14:46 UTC, brooksmtownsend commented
Thanks @autodidaddict for the comments, addressed them in the latest commit.

2021-02-08 14:41 UTC, autodidaddict approved these changes

2021-02-08 14:46 UTC, merged