Codegen roles
wasmCloud/actor-interfaces pull request #40
Opened 2021-02-09 01:48 UTC by pkedy

This was generated using the `role_operations` of `wapc/cli` which as the new roles feature for WIDL.

2021-02-09 13:22 UTC, autodidaddict requested changes
Overall this certainly looks like an improvement. However, this new generated code removes all of our rustdoc comments, which means developers would lose documentation that they're going to get when we publish these all to crates.io _today_. There's also a breaking contract on extras, and since extras is embedded in the wasmCloud host, that actually makes it so wasmCloud host would be unable to support previously compiled actors signed with the extras capability.

IMHO there's too much in-flight with the current 0.15 release and we should wait for that to complete over the next few days before we make breaking changes like this one.

2021-02-09 13:22 UTC, autodidaddict commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
Receive chunk is a handler registered by the actor, not a function we call on the host.

2021-02-09 13:22 UTC, autodidaddict commented on extras/rust/src/generated.rs
> +extern crate log;
None of the generated code ever uses the `log` crate, that's why we've been taking it out of the generated files.

2021-02-09 13:22 UTC, autodidaddict commented on extras/extras.widl
> +role Generator {
While this is certainly more simplified, it means that it will produce a breaking change in the `wasmCloud` host runtime, so we'll have to plan for that. cc @brooksmtownsend

2021-02-09 13:22 UTC, autodidaddict commented on extras/rust/src/generated.rs
> +/// Creates a named host binding
Where did this documentation come from? If we're going to rely solely on the code generator then we need the doc comments to come from the widl files, and the widl file I see above doesn't have any comments in it.

2021-02-09 13:22 UTC, autodidaddict commented on graphdb/rust/src/generated.rs
> +    pub fn query_graph(&self, graph_name: String, query: String) -> HandlerResult<QueryResponse> {
I can't tell from the diff, but @brooksmtownsend does this bust that secondary function we wrote to allow the query response to be queried into tuples?

2021-02-09 13:22 UTC, autodidaddict commented on http-server/rust/codegen.yaml
> +        - Server
This is backwards. Actors handle the request, not the host.

2021-02-09 14:21 UTC, pkedy commented
@autodidaddict Agreed on holding this off until breaking changes can be accepted. I've changed this to a Draft PR to prevent it from being merged. I really just wanted to open this as a easy way to show the diffs and progress (and also a few recommendations e.g. extras). Adding Docs from the WIDL into the generated code is what I plan on adding next. Should be pretty easy.

2021-02-09 14:22 UTC, pkedy commented on extras/rust/src/generated.rs
> +extern crate log;
Thanks! You confirmed my suspicion that it was unused.

2021-02-09 14:26 UTC, pkedy commented on http-server/rust/codegen.yaml
> +        - Server
Gotcha. I wanted to avoid just labelling everything as Actor because that's not really a role in overall conceptual model. Actors are a method of implementing said model. My thought was that the Actor was "acting" as an HTTP server and serving the requests but I also see your point in that it's really the host that is dealing with the actual HTTP protocol.

2021-02-09 14:28 UTC, pkedy commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
OK. So it's like sort of like `on_receive_chunk`. I kinda wonder if some prefix (e.g. `OnX`) for events raised by the host would resonate with developers.

2021-02-09 14:30 UTC, pkedy commented on extras/extras.widl
> +role Generator {
Totally realized these were breaking changes but went ahead with them as a recommendation while you are still pre v1.0.

2021-02-09 14:32 UTC, autodidaddict commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
We already have the "Handlers::register_receive_chunk" syntax (if the contract is written in the right direction), so I'm not sure if we need an additional "on" prefix, because then it'd be `Handlers::register_on_receive_chunk` .. :thinking:

2021-02-09 14:35 UTC, pkedy commented on extras/rust/src/generated.rs
> +/// Creates a named host binding
I'm going to add comments to one of the simple WIDLs just to get the codegen feature working. I'll let you handle the rest ;)

2021-02-09 14:38 UTC, pkedy commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
Yeah.  In theory all operations are an "OnX" to some component somewhere. ;)  _Other_ similar frameworks have an `On` prefix ;)

2021-02-09 14:41 UTC, autodidaddict commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
Developers are free to set the name of the handler functions using whatever prefix they want. However, the `on` prefix isn't all that idiomatic in Rust, certainly not like it used to be in C#.

For example, inside the `wapc_init`, they could do:

`Handlers::register_receive_chunk(on_receive_chunk);`

2021-02-09 15:08 UTC, pkedy commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
Fantastic point. I like that.

2021-02-09 15:10 UTC, pkedy commented on blobstore/rust/src/generated.rs
>      pub fn receive_chunk(&self, chunk: FileChunk) -> HandlerResult<()> {
To close the loop, I moved Receive chunk to a different role and generating handlers accordingly.

2021-02-16 19:47 UTC, brooksmtownsend reviewed
A couple comments but overall this looks _awesome_. Pretty easy to define the roles this way, and should take out a lot of the manual work that we were doing in order to get the interfaces separated by function. Now that we have our actor interfaces released and versioned, I think we can actually convert this to a regular PR and think about getting these in. Thoughts @autodidaddict ? We'd basically just need to minor version bump each one and re-release 😄

2021-02-16 19:47 UTC, brooksmtownsend commented on eventstreams/rust/codegen.yaml
> +        - Consumer
So here, the `hostRoles` is the entity that's going to be implementing the host functionality, and `handlerRoles` is the entity that's going to be registering handlers? Just making sure I'm following

2021-02-16 19:47 UTC, brooksmtownsend commented on extras/rust/src/generated.rs
> +/// Creates a named host binding
Overall it's going to be great to add documentation at the WIDL level and avoid any missed annotations in specific language modules.

2021-02-16 19:47 UTC, brooksmtownsend commented on graphdb/rust/src/generated.rs
> +    pub fn query_graph(&self, graph_name: String, query: String) -> HandlerResult<QueryResponse> {
Yes that does 😄 This will probably need to be renamed to `query` again, leaving the `query_graph` wrapper in lib.rs. If Rust allowed method overloading for visibility this wouldn't be an issue.

2021-02-16 19:47 UTC, brooksmtownsend commented on http-client/httpclient.widl
> +role Client {
As I'm reading through these, I love that the roles can be defined by any name. Not only does this seem to be nice as a generic, it lets what you're doing where you call the roles something different for each interface if we so choose when it makes sense. Awesome.

2021-02-16 19:47 UTC, brooksmtownsend commented on http-server/assemblyscript/assembly/module.ts
> +  constructor(binding: string) {
This `= "default"` isn't required necessarily for our interfaces, but it is helpful to allow assemblyscript devs to write `let blah = new Host()` without needing to know to provide the `"default"` binding. I can't remember if we discussed this, but did it make it into the codegen logic?

2021-02-16 19:47 UTC, brooksmtownsend commented on keyvalue/assemblyscript/assembly/module.ts
> +  constructor(binding: string) {
same default question as above

2021-02-16 19:47 UTC, brooksmtownsend commented on keyvalue/rust/src/generated.rs
> +        let input_args = SetRemoveArgs { key, value };
Also all of these changes look clean 👍🏻

2021-02-16 21:58 UTC, autodidaddict commented
Is the http server contract still backwards? Also want to verify that we can put comments on the role, operations, and types that can all be put in the generated code.

2021-02-16 22:54 UTC, pkedy commented on actor-core/assemblyscript/assembly/module.ts
>    placeholder: bool = false;
That came from the description in the WIDL. Its not placeholder text in the codegen.

2021-02-16 22:55 UTC, pkedy commented on eventstreams/rust/codegen.yaml
> +        - Consumer
Correct

2021-02-17 18:05 UTC, pkedy commented on http-server/assemblyscript/assembly/module.ts
> +  constructor(binding: string) {
Yeah, we did discuss this. Its a great idea. I just forgot to put it in. I will soon :)

2021-04-12 18:56 UTC, brooksmtownsend commented
Marking this as ready for review with my latest changes.

I did all of my testing using the latest version of https://github.com/wapc/cli-go (I followed the install instructions) and the codegen logic contained in this branch: https://github.com/wapc/widl-codegen-js/pull/4. I'd like @pkedy to make sure all of that logic is fine before this is merged in and we can complete these two PRs at the same time so that anybody looking to work with the WIDL files here follow the same process.

A few things that I added on top of @pkedy's role changes:
1. Updated all of the examples to use the `actorcore::init` derive macro for simplicity
2. Ensured examples are up-to-date
3. Added documentation to all of the WIDL handlers and host functions, looking to @autodidaddict to make sure I did an adequate job there 😃 
4. Fixed #70 (also bumped all interfaces by a version so we can re-publish the new docs after this, all patch versions)
5. Fixed #61 for now. We don't have a matrix build, but we're going to have to re-approach actions when we merge capability providers in here anyways. @jordan-rash do you have any objections to closing it?

**NOTE** The following Rust interfaces cannot be regenerated and still function properly:
1. Logging: We inject a good bit of custom logic for the logging interface to allow actors to use the `log` macros instead of manually calling `wasmcloud_actor_logging::write_log()`. This is the only interface that actually _requires_ custom changes to `generated.rs`.
2. GraphDB: We wrap the `query_graph` function in `lib.rs` and hide the generated `query_graph` function using the `pub(crate)` visibility modifier. The wrapper function does the ugly lifting of converting the generic graphdb type into the concrete tuple provided by the user. This isn't technically required, but if it's desired to keep this to only the generated code it's possible, we will just want to document the generic conversion code well.

2021-04-15 17:08 UTC, autodidaddict requested changes

2021-04-15 17:08 UTC, autodidaddict commented on http-client/rust/README.md
> +#[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on http-client/rust/src/lib.rs
> +//! #[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on http-server/assemblyscript/Makefile
> +#build:
delete

2021-04-15 17:08 UTC, autodidaddict commented on http-server/rust/README.md
> +#[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on http-server/rust/src/lib.rs
> +//! #[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on keyvalue/assemblyscript/Makefile
> +#build:
delete

2021-04-15 17:08 UTC, autodidaddict commented on keyvalue/keyvalue.widl
> +    Add a given numeric value to a key
Should indicate that this is an atomic operation, e.g. `Performs an atomic addition on the value currently stored in this key`

2021-04-15 17:08 UTC, autodidaddict commented on keyvalue/keyvalue.widl
> +    Returns a value stored at a key if it exists
`Indicates if a key exists` (this operation is not intended to return the current value..)

2021-04-15 17:08 UTC, autodidaddict commented on keyvalue/rust/Makefile
> +build:
libraries used by providers and actors alike should not be compiled into `.wasm` files.

2021-04-15 17:08 UTC, autodidaddict commented on keyvalue/rust/README.md
> +#[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on logging/rust/README.md
> +#[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on logging/rust/src/lib.rs
> +//! #[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on messaging/messaging.widl
> +    delivered via an active subscription or through a direct actor call
We should remove the second sentence here. It can be very misleading to encourage actor-to-actor comms that pretend to be messages from another provider.

2021-04-15 17:08 UTC, autodidaddict commented on messaging/rust/README.md
> +#[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on messaging/rust/src/lib.rs
> +//! extern crate wasmcloud_actor_core as actorcore;
actor

2021-04-15 17:08 UTC, autodidaddict commented on messaging/rust/src/lib.rs
> +//! #[actorcore::init]
`actor::init`

2021-04-15 17:08 UTC, autodidaddict commented on telnet/rust/README.md
> +#[actorcore::init]
`actor::init`

2021-04-15 19:11 UTC, brooksmtownsend commented on actor-core/assemblyscript/Makefile
> +#build:
I'm not sure why this is commented out, we should provide these make steps to build these actors. I'm going to put them back in, the only steps that shouldn't exist are the ones where we've made manual changes to Rust libraries and we should not codegen again.

2021-04-15 19:13 UTC, brooksmtownsend commented on actor-core/assemblyscript/Makefile
> +#build:
Ah I understand now... those build scripts attempt to create a wasm file. They should be removed

2021-04-15 19:37 UTC, brooksmtownsend commented on keyvalue/keyvalue.widl
> +    Add a given numeric value to a key
This might be atomic, but is it guaranteed to be atomic? e.g. could this interface be implemented in a way that's non-atomic

2021-04-15 19:45 UTC, brooksmtownsend commented on http-client/rust/Makefile
> +build:
Yep, changed this to just build the library not the wasm file

2021-04-16 15:19 UTC, autodidaddict approved these changes

2021-04-16 15:36 UTC, autodidaddict commented on keyvalue/keyvalue.widl
> +    Add a given numeric value to a key
I've been going on the assumption that this contract requires an atomic add. It could be potentially disastrous if the one underlying db didn't do this atomically and another one did

2021-04-16 15:36 UTC, autodidaddict commented on keyvalue/keyvalue.widl
> +    Add a given numeric value to a key
But I think that documentation is probably more appropriate in the capability provider doc and not the interface doc.

2021-04-16 15:42 UTC, brooksmtownsend commented on keyvalue/keyvalue.widl
> +    Add a given numeric value to a key
Yeah, we should certainly enforce the atomic add with our implementations.

2021-04-16 15:45 UTC, merged