Improved READMEs
wasmCloud/actor-interfaces pull request #52
Opened 2021-02-12 20:19 UTC by brooksmtownsend

Updated all READMEs with appropriate badges, including test status, crates.io version, etc. The main README got the biggest overhaul where the table now has badges and links to the appropriate package manager versions. We should be able to re-use this structure in the future to fill out the table completely.

We also tended to have some drift with our actor interface names, so I standardized the READMEs to all be in the form of:
```
wasmCloud <interface> Actor Interface
```
Just to keep everything uniform across the different packages. Once this is merged to `main`, all of the affected packages with changed READMEs will be re-published (I've bumped patch versions in these folders to indicate this).

I highly recommend poking around at this branch in GH to see what the README's look like https://github.com/wasmCloud/actor-interfaces/tree/improved-readme

2021-02-12 20:41 UTC, autodidaddict requested changes

2021-02-12 20:41 UTC, autodidaddict commented on README.md
> +| [Core](./actor-core/core.widl) | [![Crates.io](https://img.shields.io/crates/v/wasmcloud-actor-core)](https://crates.io/crates/wasmcloud-actor-core) | ![GitHub go.mod Go version (subdirectory of mo
When I click the go badge, it takes me to the picture of the badge and not the Tinygo sub-directory.

2021-02-12 20:41 UTC, autodidaddict commented on http-server/rust/README.md
>  This crate provides waSCC actors with an interface to the HTTP Server capability provider. Actors using this
s/wascc/wasmcloud

2021-02-16 16:13 UTC, brooksmtownsend commented on README.md
> +| [Core](./actor-core/core.widl) | [![Crates.io](https://img.shields.io/crates/v/wasmcloud-actor-core)](https://crates.io/crates/wasmcloud-actor-core) | ![GitHub go.mod Go version (subdirectory of mo
It will now take you to the pkg.go.dev URL 😄

2021-02-16 17:51 UTC, autodidaddict approved these changes

2021-02-16 17:52 UTC, merged