Blobstore interface for tinygo and assemblyscript
wasmCloud/actor-interfaces pull request #62
Opened 2021-03-19 18:37 UTC by brooksmtownsend

Weekend safety draft PR, in case laptop is thrown into a fire.

These interfaces are working for AS and TinyGo (verified with FS provider) however there are still some polish items that are needed before this is merged in.
- [ ]  Update main repository README with badges
- [ ]  Update AS README with example
- [ ]  Update TinyGo README with example
- [ ]  Update main.go + index.ts to remove unnecessary codegen artifacts

If I'm missing something else that I need to do, feel free to drop a comment if you see this

2021-03-22 20:01 UTC, brooksmtownsend commented
Updated READMEs for both interfaces and included badges on the main README, @billyoung let me know if I used that `npm` action correctly 🙂

2021-03-22 20:31 UTC, autodidaddict requested changes

2021-03-22 20:31 UTC, autodidaddict commented on blobstore/assemblyscript/README.md
> +This crate provides wasmCloud actors with an interface to the blobstore capability provider.
We should refrain from calling assemblyscript packages "crates" :)

2021-03-22 20:31 UTC, autodidaddict commented on blobstore/assemblyscript/README.md
> +import { Host as Blob, ContainerBuilder, FileChunk, FileChunkBuilder, Handlers as BlobHandlers } from "../../../../../github.com/wasmcloud/actor-interfaces/blobstore/assemblyscript/assembly/module";
This is a pretty brutal looking import. Is there a way to make this cleaner looking?

2021-03-22 20:31 UTC, autodidaddict commented on blobstore/assemblyscript/README.md
> +import { Host as Blob, ContainerBuilder, FileChunk, FileChunkBuilder, Handlers as BlobHandlers } from "../../../../../github.com/wasmcloud/actor-interfaces/blobstore/assemblyscript/assembly/module";
Since this is in the readme, it doesn't need to compile so we can show what the final version of the import looks like importing from `@wasmcloud/actor-blobstore` (or whatever the package will be called)

2021-03-22 20:31 UTC, autodidaddict commented on blobstore/go/README.md
> +This crate provides wasmCloud actors with an interface to the blobstore capability provider.
Go doesn't have crates ;)

2021-03-22 20:31 UTC, autodidaddict commented on blobstore/go/README.md
> +  blob.Handlers{ReceiveChunk: receiveChunk}.Register()
Looks like a tab-v-spaces indentation issue here.

2021-03-22 20:31 UTC, autodidaddict commented on blobstore/go/README.md
> +var blobStore *blob.Host
Do we really want to show people a global-scoped variable in our sample actors?

2021-03-22 20:37 UTC, brooksmtownsend commented on blobstore/assemblyscript/README.md
> +This crate provides wasmCloud actors with an interface to the blobstore capability provider.
Addressed in PR

2021-03-22 20:37 UTC, brooksmtownsend commented on blobstore/assemblyscript/README.md
> +import { Host as Blob, ContainerBuilder, FileChunk, FileChunkBuilder, Handlers as BlobHandlers } from "../../../../../github.com/wasmcloud/actor-interfaces/blobstore/assemblyscript/assembly/module";
Ooh good catch... I updated package.json with the appropriate name too.

2021-03-22 20:37 UTC, brooksmtownsend commented on blobstore/go/README.md
> +This crate provides wasmCloud actors with an interface to the blobstore capability provider.
Addressed in PR

2021-03-22 20:38 UTC, brooksmtownsend commented on blobstore/go/README.md
> +  blob.Handlers{ReceiveChunk: receiveChunk}.Register()
Addressed in PR, damn you different types of whitespace

2021-03-22 20:38 UTC, brooksmtownsend commented on blobstore/go/README.md
> +var blobStore *blob.Host
I adopted this from some other sample that I saw... I agree that it's better to keep it locally scoped. addressed 👍🏻

2021-03-23 15:08 UTC, autodidaddict commented
Needs more :burrito:

2021-03-23 15:09 UTC, autodidaddict approved these changes

2021-03-23 15:55 UTC, merged