fix(Request.path_segments): small test to clarify expected behavior
wasmCloud/actor-interfaces pull request #80
Opened 2021-04-25 21:18 UTC by matthewtgilbride

2021-04-25 21:29 UTC, matthewtgilbride reviewed
Does it make sense to add additional complexity to this function?  I've seen http server libraries go two ways:

`/path/to/somewhere` and `/path/to/somewhere/` are routed identically by the library.

vs:

`/path/to/somewhere` and `/path/to/somewhere/` are technically two separate routes, and the user is left to handle things according to their requirements.

This tripped me up with my implementation because I was pattern matching on `segments.get(0)`, expecting a `None` at the root route when in fact it is always `Some("")`, since the current implementation of the first party capability provider always sends at least one `/` in the raw `path` field (AFAICT).

2021-04-25 21:29 UTC, matthewtgilbride commented on http-server/rust/src/lib.rs
> +    fn single_slash() {
This test will fail because `path_segments` returns `[""]`

2021-04-25 21:29 UTC, matthewtgilbride commented on http-server/rust/src/lib.rs
> +    fn trailing_slash() {
This test will fail because `path_segments` returns `["foo", ""]`

2021-04-27 14:53 UTC, brooksmtownsend reviewed
I don't have a strong opinion either way, but if I had to pick I'd err on the side of handling `/test/` differently than `/test`, just to avoid any unexpected behavior. Any thoughts here @autodidaddict @ChrisRx ? Regardless, if the current behavior is what we want, we can also setup these tests denoting they _should_ fail, and it will illustrate behavior.

Thanks for this PR @matthewtgilbride ! 🔥

2021-04-28 12:58 UTC, autodidaddict requested changes
After making the new behavior remove the trailing slash, if there is one, from the path prior to split in `path_segments`, this LGTM.

2021-04-28 12:58 UTC, autodidaddict commented on http-server/rust/src/lib.rs
> +    fn single_slash() {
Rather than having a failing test, which in turn causes the entire build to fail, assert the negative so the test passes.

2021-04-28 12:58 UTC, autodidaddict commented on http-server/rust/src/lib.rs
> +    fn trailing_slash() {
Like @brooksmtownsend - we should modify the path segments function to trim the trailing `/` before split so that `"/foo/"` will return `["foo"]`.

2021-04-28 12:58 UTC, autodidaddict commented on http-server/rust/src/lib.rs
> +    fn single_slash() {
We can make this test pass by doing the small suggestion made in the other comment - remove the trailing slash, if one exists, from the path string prior to split.

2021-04-28 13:52 UTC, brooksmtownsend commented on http-server/rust/src/lib.rs
> +    fn trailing_slash() {
So in the following three cases:
1. `"/foo"`
1. `"/foo/"`
1. `"foo/"`

The result should always be `["foo"]`? Just want to make sure we have that behavior well defined

2021-05-03 19:25 UTC, matthewtgilbride commented
Sorry for the intermittent activity on my end....what am I not getting through my thick skull here (tests still fail)?
https://github.com/wasmCloud/actor-interfaces/pull/80/commits/9b6f285edac88a2162a74aeb0c26eef75cfb55c1

2021-05-03 21:15 UTC, matthewtgilbride commented
> Sorry for the intermittent activity on my end....what am I not getting through my thick skull here (tests still fail)?
> [9b6f285](https://github.com/wasmCloud/actor-interfaces/commit/9b6f285edac88a2162a74aeb0c26eef75cfb55c1)

Nevermind....TIL `trim_end_matches`

2021-05-03 21:18 UTC, matthewtgilbride commented on http-server/rust/src/lib.rs
> +    fn trailing_slash() {
@brooksmtownsend that's what the current iteration of this PR is going to do.  AFAIK it's somewhat common, because there isn't really a legitimate reason to append a `/` to a path unless there are _more_ segments to a path.  And it kind of follows that developers of API's want to "be liberal in what they accept and conservative in what they produce" (I forget where the quote comes from).  So, for instance, if a user sends `/path/to/thing/?queryParam` as opposed to `/path/to/thing?queryParam`, their intentions are known and it's preferable not to have the former result in a 404.

2021-05-05 13:04 UTC, brooksmtownsend requested changes

2021-05-05 13:04 UTC, brooksmtownsend commented on http-server/rust/src/lib.rs
> +
@matthewtgilbride Thank you for throwing these tests in! Would you mind throwing in one more test that tests for a few path arguments? e.g. asserting that:
```
let request = test_request("/foo/bar/baz/");
```
appropriately retrieves the three segments?

2021-05-05 13:04 UTC, brooksmtownsend commented on http-server/rust/src/lib.rs
> +
Otherwise, LGTM 👍🏻

2021-05-05 13:50 UTC, autodidaddict approved these changes

2021-05-05 13:52 UTC, brooksmtownsend approved these changes
Once the tests pass LGTM 🚀

2021-05-05 14:41 UTC, merged