Httpclient smithy
wasmCloud/actor-interfaces pull request #85
Opened 2021-07-22 18:35 UTC by stevelr

Addresses issue #116 port http-client widl interface to smithy

2021-07-22 18:39 UTC, stevelr commented
sorry about the messy branch history. This branch is based on main and is independent of the builtin/numbergen PR

2021-07-23 12:24 UTC, autodidaddict requested changes

2021-07-23 12:24 UTC, autodidaddict commented on http-client/rust/src/lib.rs
> +//! org.wasmcloud.provider.httpclient
This crate is going to be published on crates[dot]io, so it should have a full set of module-level documentation just like the old module, which should include an example of what it looks like to create an actor that uses this module.

2021-07-23 12:24 UTC, autodidaddict commented
You'll also need to fix the DCO status

2021-08-06 18:53 UTC, brooksmtownsend commented
@stevelr where are we with this PR? Is it still being worked on?

2021-08-08 10:00 UTC, stevelr commented
It's still open but paused because it's slightly  lower priority than getting httpserver, keyvalue, and numbergen working with unit tests, documentation, and sample actor code.

2021-08-11 15:07 UTC, stevelr commented
converted to draft pr

2021-08-19 22:42 UTC, closed without merging